README.md
index.js

tag lts releases

---

index.js
test/index.js

this is useful so when you pass `--runtime=electron --target=50` to prebuild it still works

return abi if passed as target

---

README.md
index.js
package.json
test/index.js

I need this for prebuild, also api symmetry <3

Add .getTarget(abi, runtime)

---

index.js
test/index.js

fix case where there is no electron match

---

index.js

electron is now under 1.6.0 beta

support for electron 1.6.0 beta

---

README.md
index.js

this adds all missing versions

add missing abi versions to targets

---

README.md
index.js

Add `futureTargets`

---

index.js

https://github.com/electron/electron/releases/tag/v1.8.0

Add support for Electron 1.8

---

index.js

https://nodejs.org/en/download/releases/
https://github.com/nodejs/Release

fix(Node): Add support for Node 9

---

index.js

Closes https://github.com/lgeiger/node-abi/issues/36

Add Electron 2.0.0(-beta.1) to future targets

---

index.js

Add support for Electron 3.0.0 release

---

index.js

See: https://github.com/electron/electron/pull/16687

feat: add ABI number for Electron ^4.0.4

---

index.js

Add future electron 7 beta abi.

feat: add abi version for electron 7

---

index.js

feat: Support Electron 9

---

abi_registry.json
scripts/update-abi-registry.js

fix: some electron releases have multiple ABI numbers and some electron releases share ABI numbers

---

CONTRIBUTING.md

Based off of Electron Packager's "Filing a pull request" guide.

chore: add PR guidelines to CONTRIBUTING.md

---

package.json

updates incorrect metadata to correct metadata :)

fix: update repo in package.json

---

.circleci/config.yml

build: use CircleCI cimg/node images

---

package.json

build: only publish necessary files

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update-abi.yml
.releaserc.json
CONTRIBUTING.md
package.json
yarn.lock

https://docs.npmjs.com/trusted-publishers

ci: use npm trusted publishing instead of CFA

---

.github/workflows/release.yml

build: actually run semantic release
