- README.md
- index.js
Fix https://github.com/lgeiger/node-abi/pull/3#discussion_r97977698
Reference: https://github.com/nodejs/LTS
> Fix: Both Node 4 and 6 are active LTS at the moment

- index.js
We use this module in `electron-rebuild` and some people hit the issue recently where Electron `1.6` came out and their existing install threw an error saying it failing to map the ABI version.  This message will help users more rapidly identify a potential solution to this issue. 👍
> Provide a slightly more user friendly error message

- index.js
Node 8 will be released later to day and will have [`ABI 55`](https://github.com/nodejs/node/blob/d74a545535868380b028c27dfcdf54e2d5f7c563/src/node_version.h#L76).
> Add support for Node 8

- .travis.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- package.json
With this in place [`semantice-release`](https://github.com/semantic-release/semantic-release) will automatically release new versions on Travis. This will allow us to ship a lot quicker when new versions of Electron or Node are released.
It will determine the version depending on the git commit messages. How to properly format the messages is described in the [new contributing guide](https://github.com/lgeiger/node-abi/blob/57680f29ffe0dd4df2dc2145cd95d170bdec8f9d/CONTRIBUTING.md).
> Use semantic release to automate the release process

- README.md
- index.js
- test/index.js
This PR adds support to node-webkit target, necessary to build native modules when using NW.js, an Electron alternative.
Tests are included.
NW.js apparently does not follow a specific versioning pattern to switch ABI, so the `getNextTarget` function can't be implemented correctly for `node-webkit`, so I left it untouched.
> Add support to node-webkit target.

- index.js
[Electron 2.0.0](https://github.com/electron/electron/releases/tag/v2.0.0) was released this week.
> fix(electron): move Electron 2.0 to the supported list

- index.js
Version 5.0 of `prebuild-install` dropped support for Node 4 so it doesn't make sense to include it in `supportedTargets` since we use this list to determine for wich distributions to build.
This commit also updates the LTS schedule.
/cc @ralphtheninja @mafintosh @juliangruber
> fix: Move Node 4 to deprecated targets and update LTS schedule

- index.js
closes #52 
[electron@4.0.0](https://github.com/electron/electron/releases/tag/v4.0.0) is out.
> Add electron 4.0.0

- index.js
chained comparisons don't work in node, `a < b < c` is equivalent to `(a < b) < c`, i.e. coerce the boolean `(a < b)` to an integer (0 for false, 1 for true) and then compare that to `c`. So this `lts` test would always have been `true`, since both `0` and `1` are less than `+new Date(2020, 4, 31)`
> fix bug with lts computation for node 10

- index.js
- test/index.js
I think the details are correct here, based on the details in https://nodejs.org/en/download/releases/. and https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json
Let me know if anything is unclear.
> add entries for Node 12 and Electron 5

- index.js
https://github.com/nodejs/Release recently marked Node 12 as an active LTS, so I figure I'd flag that in here while I was poking around.
These should be the bounds specified for the date (converted for convenience):
I wasn't quite clear on the rules on what's set for Node 10 as I think that's off by a month, because **the `month` parameter in the `Date` constructor is zero-based** 😱:
I think that second date should be `new Date(2020, 3, 31)` (to indicate the end of April), rather than the end of May, but let me know if there's some context I'm missing.
> indicate Node 12 is an LTS release

- index.js
Since the 31st of April is over, we can now set it to `false` :slightly_smiling_face:
> chore: Set LTS for Node 8 to false

- index.js
Registered Electron 8 abi according to https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json
Fixes https://github.com/lgeiger/node-abi/issues/77
> feat: add support for Electron 8 stable

- index.js
- test/index.js
This PR adds electron 10.0.0-beta.1 as a future target so we can build and package apps with this version of electron without a problem.
> Add electron 10.0.0-beta.1 target

- .github/workflows/update-abi.yml
- abi_registry.json
- index.js
- package.json
- scripts/update-abi-registry.js
- test/index.js
Uses the following sources to autogenerate a relatively recent ABI registry on a daily basis and commit the changes to master:
* [`abi_version_registry.json`](https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json) from Node.js
* [Node.js release (+ LTS) schedule](https://github.com/nodejs/Release/blob/master/schedule.json)
* [`lite.json`](https://github.com/electron/releases/blob/master/lite.json) from `electron-releases`
This should avoid the issues generated whenever a new major Node/Electron version is released.
The GitHub Action is based on something similar I created for [Electron Fiddle](https://github.com/electron/fiddle/pull/331).
> feat: use autogenerated ABI target list

- .github/workflows/update-abi.yml
* auto-updating commits are from GitHub Actions (not @MarshallOfSound)
* auto-updating commits have a more generalized commit message, with `feat:` to trigger minor releases
* fixes a bug in auto-updating where `npm install`'s package-lock.json` prevented commits due to a "dirty" status
Merging this should actually trigger a release (as a previous auto-commit did not).
> fix: various fixes for the ABI registry updater

- index.js
A comparator function for `Array.sort` should return:
- a value less than zero if `a` is less than `b`
- zero if `a` is equal to `b`
- a value greater than zero if `a` is greater than `b`
The previous implementation of the comparator function (introduced in #95) could only ever return true/false, i.e. 1/0 but no -1. So, what I think happened was that when 0 was returned, Node attempted to apply a default ordering on the objects based on the values of all their properties. That is why a seemingly innocuous change such as changing an `lts` property from `false` to `true` resulted in a broken order. I guess the order was previously correct only by accident 😄
> fix: sorting of targets

- abi_registry.json
Adds Electron 15.0.0-beta.1 to the ABI registry.
> chore: add electron 15.0.0-beta.1 to abi registry

- abi_registry.json
Fixes #114
In Node 17.0.0, a header is missing and causes an error during compilation. This was a [known problem](https://github.com/nodejs/node/issues/40529) solved in version 17.0.1; this PR updates the target to point at the fixed version.
> fix: update node 17 to 17.0.1

- .github/workflows/update-abi.yml
Updates and pins SHAs for actions. Should clear deprecation warnings on workflow runs.
> ci: update GitHub actions workflow

- .github/workflows/update-abi.yml
Changed as per these instructions: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci: update usage of deprecated ::set-output

- scripts/update-abi-registry.js
Per documentation (https://github.com/jsdelivr/jsdelivr#caching), the default URL (alias for `@latest`) caches for 7 days, while specifying branches only caches for 12 hours.
> chore: use main branch with cdn.jsdelivr.net for shorter caching

- abi_registry.json
- scripts/update-abi-registry.js
The last couple of automated releases didn't have any content change, but were triggered by the sorting order of `abi_registry.json` changing. Enforce a stable ordering by first sorting by ABI (current behavior) and then also sort by version (new behavior).
There should be no user facing changes as a result of this PR - the public API does its own sorting, this only affects the on-disk sorting of `abi_registry.json` as that's what causes new releases to trigger, when that changes.
Considered changing the sorting to be only by version, but that resulted in too much change to `abi_registry.json`. This change results in a minimal diff that is easy to verify by hand.
> build: secondary sort abi_registry.json entries by version

- yarn.lock
Clears a Dependabot security alert which it seems to be unable to open a PR for itself, for some reason.
> build(deps): update transitive dep semver from 5.7.1 to 5.7.2

- .github/workflows/check-electron-abi.yml
Workflow to make it easier to confirm `node-abi` is updated correctly after a new Electron release.
> ci: add workflow to check ABI for Electron version

- .github/workflows/update-abi.yml
Same changes as https://github.com/electron/download-stats/pull/31 and bumps the Node.js version as well.
> ci: use GitHub app for commits

- .github/workflows/update-abi.yml
Since this repo has CFA releases, it's not very useful to us if the auto-update triggers a release when no one is around to approve it. Since most core maintainers are online during US daytime hours, limit the auto-update to running between 8 AM and 8 PM PT.
> ci: restrict auto-update to more active time window

- package.json
- yarn.lock
Follow-up to #151, this package no longer needs to be in dev dependencies with the latest CFA orb.
> build: remove @continuous-auth/semantic-release-npm

- .github/workflows/check-electron-abi.yml
Just some routine maintenance, and marking the input as required which was an oversight in #144.
I've also updated this to take the expected ABI number so we can catch mistakes.
> ci: update check-electron-abi workflow

- .github/workflows/check-electron-abi.yml
- .github/workflows/update-abi.yml
Bumps versions to get things off EOL Node.js versions and preempts deprecation warnings.
> ci: update workflows

- .github/workflows/update-abi.yml
Uses the new `dsanders11/github-app-commit-action` to make the commits via the GitHub API which means they'll be marked as verified.
> ci: make signed commits

- package.json
- scripts/update-abi-registry.js
- yarn.lock
This script is only used to update the JSON in this package, so let's drop `got` and use `fetch` since we're running it on Node.js 20.
> chore: remove got dependency

- .github/workflows/update-abi.yml
#149 has worked pretty well, but we should also restrict to workdays for the same reasons.
> ci: restrict auto-update to Monday-Friday
